Больше деталей
htmlacademy-univer-javascript-1/2579379-kekstagram-5 pull request #3
Opened 2024-11-29 07:02 UTC by ValentinaKobtseva

2024-12-03 09:52 UTC, dimohqa requested changes
Хорошая работа, молодец, чуть комментов оставил, в остальном все хорошо

2024-12-03 09:52 UTC, dimohqa commented on js/main.js
> +const urlPart = getUniqueRandomValue(1, 25);
Классное решение с замыканием, молодец)

А почему решила объявить переменные в глобальной области видимости? Они ведь нужны только в функции `getPhotoDescription`

2024-12-03 09:52 UTC, dimohqa commented on js/main.js
> +const urlPart = getUniqueRandomValue(1, 25);
От названия `photoId` и вызова функции `getUniqueRandomValue` ожидаешь, что `photoId` это идентификатор, а не функция. Давай переименуем?

2024-12-03 11:05 UTC, ValentinaKobtseva commented on js/main.js
> +const urlPart = getUniqueRandomValue(1, 25);
Вообще, вынесла изначально по причине того, что, если их объявлять в getPhotoDescription, id и url генерируются с повторениями, но сейчас немного переписала, добавив еще одно замыкание и, вроде, все отлично))) Ничего не напутала?
![image](https://github.com/user-attachments/assets/c5537b77-a162-4343-a3bc-9afc5a8f837a)

2024-12-03 11:06 UTC, ValentinaKobtseva commented
Спасибо! очень приятно такое читать :))))

2024-12-04 07:46 UTC, dimohqa commented on js/main.js
> +const urlPart = getUniqueRandomValue(1, 25);
Я не заметил, что ты вызываешь эту функцию на каждый массив из-за чего у тебя каждый раз создается новая функция `getUniqueRandomValue` (соответственно столько замыканий, сколько всего элементов).

Мне не нравится такое решение тк мы породили множество не очень полезных замыканий. Лучше вернуть обратно :)

2024-12-04 07:53 UTC, dimohqa approved these changes

2024-12-04 07:53 UTC, merged